CREATE TABLE authors (
	id 					INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nick				VARCHAR(50) NOT NULL,
	email				VARCHAR(100) NOT NULL,
	password		VARCHAR(100) NOT NULL,
	role				ENUM('admin', 'editor') NOT NULL DEFAULT 'admin',
	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at	TIMESTAMP NULL DEFAULT NULL
)DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE posts (
	id 				      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_author	      INT,
	title			      VARCHAR(255) NOT NULL,
	slug			      VARCHAR(255),
  excerpt         VARCHAR(255),
	content			    TEXT NOT NULL,
	featured_image 	VARCHAR(255),
	state			      ENUM('draft','published') NOT NULL DEFAULT 'draft',
	created_at		  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at		  TIMESTAMP NULL DEFAULT NULL,
  date_pub        TIMESTAMP NULL DEFAULT NULL,

	FOREIGN KEY (id_author) REFERENCES authors(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE comments (
	id 				  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id_post			INT,
	user			  VARCHAR(100) NOT NULL,
	email			  VARCHAR(255),
  web         VARCHAR(255),
	comment 		TEXT,
	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at	TIMESTAMP NULL DEFAULT NULL,

	FOREIGN KEY (id_post) REFERENCES posts(id)
		ON UPDATE CASCADE
		ON DELETE SET NULL
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE categories (
	id 				  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name			  VARCHAR(50),
	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at	TIMESTAMP NULL DEFAULT NULL
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE tags (
	id 				  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name			  VARCHAR(50),
	created_at	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified_at	TIMESTAMP NULL DEFAULT NULL
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE poststags (
	id_post	INT NOT NULL,
	id_tag	INT NOT NULL,

	PRIMARY KEY (id_post, id_tag),

	FOREIGN KEY (id_post) REFERENCES posts(id)
		ON UPDATE CASCADE,

	FOREIGN KEY (id_tag) REFERENCES tags(id)
		ON UPDATE CASCADE
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;

CREATE TABLE postscats (
	id_post			INT NOT NULL,
	id_cat 			INT NOT NULL,

	PRIMARY KEY (id_post, id_cat),

	FOREIGN KEY (id_post) REFERENCES posts(id)
		ON UPDATE CASCADE,

	FOREIGN KEY (id_cat) REFERENCES categories(id)
		ON UPDATE CASCADE
) DEFAULT CHARACTER SET UTF8 ENGINE=InnoDB;